---
title: "Lab 7"
author: "WADDS"
date: "February 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
shelter_data <- read_csv("aac_shelter_outcomes.csv")
```
## General Question

An overall question we would like to investigate in next weeks lab is: what trends are there in animals leaving and entering a humane society and what factors lead to more animals getting adopted?

## Our Domain Expert and Importance
For our domain expert, we are going to be doing this research for the Austin Animal Shelter in Texas. By analyzing their data, we can help them to determine what factors lead to higher rates of adoption of their animals. We can also see which factors may be applicable to other animal shelters across the country. By discovering the trends present in this data set they will be able to change policy and practices to hopefully increase adoption rates and possibly decrease instances of euthanasia.

## Our Data

The data we will use to answer our questions is a dataset from Kaggle that gives information about thousands of animals admitted to the Austin Animal Center Shelter. The data set describes each animal with details including its age, gender, and condition, and outcome of the animal. This dataset can be found at the following URL: https://www.kaggle.com/aaronschlegel/austin-animal-center-shelter-outcomes-and 


## Sarah Individual
A question I would want to answer in Lab 8 is what trends are there in animals entering and leaving a humane society? A backup question would be which factors result in animals getting adopted most frequently in a humane society?

These are important questions because, with this information, a humane society could have a better idea of where to put their resources in order to maximize the number of animals they save, and they could also gain information on what steps could be taken to get more animals adopted. These questions are interesting to me because I interned at the Humane Society of Boulder Valley last spring and have been involved there ever since; it would be interesting to find out if there was any information from our data that could benefit them. Since the Austin Animal shelter has a similar mission as the Humane Society of Boulder Valley, the data from their shelter might be a good place to start. 

## Derek Individual

My primary question is are certain kinds of breeds more at risk to things like suffering, agressive behavior, or other factors that would lead to euthanasia at the shelter? My backup question is are certain breeds more likely to be returned to owner than others after accounting for the distribution of breeds?

I understand the first is a painful question to ask, but if there are correlations between breeds and these factors then breeder policies and owner education programs can be implemented to try and reduce them, and employees can be made aware of which breeds are more at risk for these factors. 

## Abby Individual

My primary question would be how age affects the outcome of the animal entering the shelter. Are older animals less or more likely to be adopted? This is an important question as it could influence adoption strategies and policies. If older animals are less likely to be adopted, then the shelter could possibly change marketing strategies. For instance, older people tend to adopt older animals, so holding an adoption day geared toward elderly people could increase adoption rates of animals who are normally left behind. 

My backup question would be how do outcomes differ across species? Are cats more likely to be adopted than birds? How do adoption rates differ among the species based on different age, color, or sex? This is an important question as it can also lead to more in-depth study of how to increase adoption rates among animals. If cats are less likely, controlling for other variables, to be adopted than dogs, a shelter could create new campaigns and events to increase cat adoption rates. These questions are important because finding answers could lead to overall higher adoption rates of animals, which could also lead to a decrease in euthanasia. 

## David Individual Part 

My primary question is: 
Do different types of animals have different outcomes of entering the shelter, and how do different kinds of animals have different abilities to adapt? Since we can investigate this problem from age and sex and different outcomes and give consumers information for what they want to breed.

My backup question is:
Does classifcation of cats help them get better service? For example, we could classify different kinds of cat by ages. The cats with younger age could adopt much more quickly than adult cats, and younger cats could have more convenience service than others. For example like therapy.

## Will Individual Part
My primary question comes up with how breed of dog/cats will affect the sex_upon_outcome of animals that enter into the Austin Animal center? My backup question is are certain breeds of animals are more likely to enter into the Austin Animal center?

These are important questions because the result could show the probability of different kinds of breeds of cats/dogs entering with a certain processed sex entering into the Austin Animal center. It will give us the statement to know what kinds of breeds we need to protect, because when we work with their sex_upon_outcome, they probably could not live in a human society anymore, so that they need to come into the animal shelter. Obviously, it is a good study for telling everyone that has pets with dogs/cats to treat their pets wisely. 

