---
title: "Lab 12"
author: "Sarah Liddle"
date: "April 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
library(tidyverse)
library(gapminder)
library(stringr)

gapminder2<-gapminder %>% mutate(decade=parse_character(year))
gapminder2$decade<-str_c(str_extract(gapminder2$decade, "^..."),"0")
gapminder2<-gapminder %>% mutate(decade=parse_factor(gapminder2$decade,c("1950","1960","1970","1980","1990","2000")))
```

## Life Expectancy


```{r statslife}
stat_lifeExp<-function(data, continent0, decade0){
  newdat<-filter(data, continent==continent0 & decade==decade0)
  min0<-min(newdat$lifeExp)
  max0<-max(newdat$lifeExp)
  mean0<-mean(newdat$lifeExp)
  median0<-median(newdat$lifeExp)
  IQR0<-IQR(newdat$lifeExp)
  stats<-list(min=min0, max=max0, mean=mean0, median=median0, IQR=IQR0)
  return(stats)
}

cont_lifeExp<-tibble(continent=character(0), decade=character(0), minLifeExp=numeric(0), maxLifeExp=numeric(0), meanLifeExp=numeric(0), medianLifeExp=numeric(0), IQRLifeExp=numeric(0))
for (i in (1:length(levels(gapminder2$continent)))){
  cont<-levels(gapminder2$continent)[[i]]
  for (j in (1:length(levels(gapminder2$decade)))){
    dec<-levels(gapminder2$decade)[[j]]
      row<-length(levels(gapminder2$decade))*(i-1)+j
      stats<-stat_lifeExp(gapminder2, cont, dec)
      cont_lifeExp[row,]<-c(cont,dec, stats[[1]], stats[[2]],stats[[3]],stats[[4]],stats[[5]])
  }
}

print("Ordered by Mean")
cont_lifeExp[order(cont_lifeExp$meanLifeExp),]
print("Ordered by Median")
cont_lifeExp[order(cont_lifeExp$medianLifeExp),]

```

## GDP Per Capita


```{r statsgdp}
stat_gdpPercap<-function(data, continent0, decade0){
  newdat<-filter(data, continent==continent0 & decade==decade0)
  min0<-min(newdat$gdpPercap)
  max0<-max(newdat$gdpPercap)
  mean0<-mean(newdat$gdpPercap)
  median0<-median(newdat$gdpPercap)
  IQR0<-IQR(newdat$gdpPercap)
  stats<-list(min=min0, max=max0, mean=mean0, median=median0, IQR=IQR0)
  return(stats)
}

cont_gdpPercap<-tibble(continent=character(0), decade=character(0), mingdp=numeric(0), maxgdp=numeric(0), meangdp=numeric(0), mediangdp=numeric(0), IQRgdp=numeric(0))
for (i in (1:length(levels(gapminder2$continent)))){
  cont<-levels(gapminder2$continent)[[i]]
  for (j in (1:length(levels(gapminder2$decade)))){
    dec<-levels(gapminder2$decade)[[j]]
      row<-length(levels(gapminder2$decade))*(i-1)+j
      stats<-stat_gdpPercap(gapminder2, cont, dec)
      cont_gdpPercap[row,]<-c(cont,dec, stats[[1]], stats[[2]],stats[[3]],stats[[4]],stats[[5]])
  }
}
print("Ordered by Mean")
cont_gdpPercap[order(cont_gdpPercap$meangdp),]
print("Ordered by Median")
cont_gdpPercap[order(cont_gdpPercap$mediangdp),]

```


## Answering a Question

``` {r question}

all<-full_join(cont_gdpPercap,cont_lifeExp)
all$meangdp<-as.numeric(all$meangdp)
all$meanLifeExp<-as.numeric(all$meanLifeExp)
all$medianLifeExp<-as.numeric(all$medianLifeExp)
all$decade<-as.numeric(all$decade)
ggplot(data=all)+geom_point(aes(x=meangdp,y=meanLifeExp,color=continent))+geom_smooth(aes(x=meangdp,y=meanLifeExp,color=continent),se=FALSE)
ggplot(data=all)+geom_point(aes(x=decade,y=meanLifeExp,color=continent))+geom_smooth(aes(x=decade,y=meanLifeExp,color=continent),se=FALSE)
ggplot(data=all)+geom_point(aes(x=decade,y=meangdp,color=continent))+geom_smooth(aes(x=decade,y=meangdp,color=continent),se=FALSE)
ggplot(data=all)+geom_smooth(aes(x=decade,y=medianLifeExp,color=continent))+geom_smooth(aes(x=decade,y=meanLifeExp,color=continent),se=FALSE)

```






